name: Build

on:
  push:
    branches: [latest]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/takermanltd/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --verbosity normal

      - name: Pack and Publish
        run: |
          dotnet nuget locals all --clear
          for csproj in $(find . -name '*.csproj'); do
            dotnet pack "$csproj" --output nupkg
            dotnet nuget push "nupkg/*.nupkg" --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
          done
          
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@TAKERMANLTD'
      - name: Build Vue framework
        working-directory: ./takerframework
        run: npm ci
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}