name: Build

on:
  push:
    branches: [latest]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/takermanltd/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@takermanltd'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build project
        run: dotnet build --configuration Release

      - name: Create Notifications package
        working-directory: ./Takerman.Notifications
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR
        run: dotnet nuget push Takerman.Notifications/bin/Release/*.nupkg --skip-duplicate
      
      - name: Create Auth package
        working-directory: ./Takerman.Auth
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR
        run: dotnet nuget push Takerman.Auth/bin/Release/*.nupkg --skip-duplicate
  
      - name: Create Blogging package
        working-directory: ./Takerman.Blogging
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR
        run: dotnet nuget push Takerman.Blogging/bin/Release/*.nupkg --skip-duplicate

      - name: Create Dating package
        working-directory: ./Takerman.Dating
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR
        run: dotnet nuget push Takerman.Dating/bin/Release/*.nupkg --skip-duplicate

      - name: Create Marketplace package
        working-directory: ./Takerman.Marketplace
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR
        run: dotnet nuget push Takerman.Marketplace/bin/Release/*.nupkg --skip-duplicate

      - name: Build Vue framework
        working-directory: ./takerframework
        run: npm ci
      - name: Publish Vue package
        working-directory: ./takerframework
        run: npm publish --skip-existing