name: Build

on:
  push:
    branches: [latest]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
          source-url: https://nuget.pkg.github.com/takermanltd/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build project
        run: dotnet build --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR
        run: dotnet nuget push Takerman.Mail/bin/Release/*.nupkg