name: Build

on:
  push:
    branches: [latest]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/takermanltd/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --verbosity normal

      - name: Pack and Publish
        run: |
          dotnet nuget locals all --clear
          mkdir -p nupkg
          for csproj in $(find . -name '*.csproj'); do
            dotnet pack "$csproj" --output nupkg
            dotnet nuget push "nupkg/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          done
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@TAKERMANLTD'
      - name: Build Vue framework
        working-directory: ./takerframework
        run: npm ci
      - name: Check if version exists
        working-directory: ./takerframework
        id: check-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          PKG_NAME=$(node -p "require('./package.json').name")
          EXISTS=$(npm view "$PKG_NAME@$VERSION" version)
          echo "PKG_EXISTS=$EXISTS" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          
      - name: Publish to npm
        if: env.PKG_EXISTS == ''
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}